# Generated by Django 4.2.2 on 2023-06-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FirstApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
