# Generated by Django 4.2.2 on 2023-06-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FirstApp", "0002_blog_is_public"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="is_public",),
    ]
