# Generated by Django 4.2.2 on 2023-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FirstApp", "0003_remove_blog_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
